name: PyTest
on:
  pull_request:
    paths:
      - "tests/**"
      - "src/**"
      - "uv.lock"
      - .github/workflows/pytest.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup Python (faster than using Python container)
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: |
          uv sync --frozen

      - name: Run test suite
        run: |
          uv run pytest tests/ -vv